### ISSUE TITLE
[Frontend] Create Wrapper

### ISSUE THREAD

**Issue by ccdc-git** [swsnu/swpp2021-team9#17]
### Feature description
Wapper 만들기
Header
- [x] view 그리기
- [x] button onclick 연결

PlayerBar
- [x] progress 표시
- [x] 버튼 연결
- [x] view 그리기

Player
- [x] 여러 audio를 한번에 재생
- [x] 다음, 이전, 멈춤 컨트롤
- [x] track 추가

### Screenshots / Additional context
icon같은 resource는 res에 저장했습니다.
types.d.ts에 global로 쓰일 만한 type들 모아놨습니다.

app/helper에 도움이 될만한 코드들 모았습니다.

#### TrackPlayer
private audios: HTMLAudioElement[]
private track?: TrackInfo
private status: 'init' | 'loading' | 'loadFinish' | 'pause' | 'playing'
onStatusChange?: (status: string) => void;
- setTrack(track)
재생할 track 을 설정
- isPaused()
멈춤 (every audio is paused)
- play()
동시 재생
- pause()
동시 멈춤
- getDuration()
전체 플레이 시간 (max of audio.duration)
- getCurrentTime()
현재 재생 시간 (max of audio.currentTime)
- getMinReadyState()
현재 오디오 상태 (min of audio.readyState)

#### Player
기본적으로 TrackPlayer의 Singletone과 tracks 관리를 더한 것.
- static getInstance()
어디서든지 같은 player 가져오기
- setIndex()
track index로 재생
- setTracks(tracks: TrackInfo[])
새로운 tracks를 가져오고 첫번째 재생
- addTrack(TrackInfo)
새로운 track을 현재 재생 이전에 추가하고 바로 재생
- playNext()
다음 곡 재생
- playPrev()
이전 곡 재생

![image](https://user-images.githubusercontent.com/5417636/140925572-96292ffd-e46a-443e-b3d2-a1f6f4f9f559.png)

**Comment by zz-zye** [comment]
PR 머지하면서 이슈 닫습니다

**Comment by ccdc-git** [comment]
testing 때문에 다시 열었습니다.

**Comment by zz-zye** [comment]
이제 test까지 끝나서 merge합니다!
