### ISSUE TITLE
[Frontend] Base URL

### ISSUE THREAD

**Issue by GoGiants1** [swsnu/swpp2021-team9#26]
### Feature description
- tsconfig에 path 추가하기. 이걸 하면 '@/folder명'으로 import 가능(절대경로?)

### Screenshots / Additional context
![image](https://user-images.githubusercontent.com/69342392/141146705-d74fe7c0-1a58-424c-98cc-fa86a447a515.png)

**Comment by GoGiants1** [comment]
아 이건 바꿔도 기존 타입스크립트 컴파일러 세팅? 때문에 원래로 돌아가네요.

그리고 절대경로를 base url 기준으로 사용 할 수 있는걸 이제 확인했습니다.

`app/components/CreateCover/*.tsx`형식으로 사용하거나 폴더에 index.ts 파일을 만들고 `export { default as 원하는 이름} from './파일명` 형식으로 적어두면 `app/components/CreateCover`와 같은 url로 import 할 수 있습니다. 다만 이때는 default export로 인식하는게 아니라서 import {정해놓은 이름(원하는 이름)} from '폴더명'으로 import하면 되는군요. 개인적으로 이해한 김에 이슈에 적어서 남겨봅니당

**Comment by zz-zye** [comment]
앗 넵 `app/`이나 `utils/` 등으로 시작하는 경로를 통해 import가 가능합니다!

**Comment by zz-zye** [comment]
Sprint 3이 끝나서 닫겠습니다!
