### ISSUE TITLE
SonarCloud Code Smells

### ISSUE THREAD

**Issue by zz-zye** [swsnu/swpp2021-team9#56]
### Description
Should refactor and remove SonarCloud Code Smells

### Screenshots / Additional context
![image](https://user-images.githubusercontent.com/77932817/143426081-7cfe0291-0490-4e28-9b05-97175c173a7f.png)

### How to solve

Each person should refactor the code smells assigned to them as shown in the SonarCloud code smell screen.   
Each person should open a branch to solve their code smells and make PRs.

![image](https://user-images.githubusercontent.com/77932817/143427998-7a5de082-b4f0-4565-b0bd-34a10eb79111.png)

By December 2nd, all 89 Code Smells (or all of the code smells left in that time) should be solved.

**Comment by GoGiants1** [comment]
- frontend/src/app/components/CreateCover/YoutubePlayer.tsx: 22 code smells. comment out한 코드 제거.
 -  frontend/src/app/containers/CreateCoverPage/step1.tsx: 16 code smells. 사용하지 않은 변수 제거.
 - ![image](https://user-images.githubusercontent.com/69342392/143429394-4d421bf8-c5e8-4771-9dfd-d829cc3ee5f5.png)

**Comment by zz-zye** [comment]
Should not close until all 4 branches are merged..
